services:
  zadarma:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    networks:
      - webnet
    volumes:
      - .:/var/www/html  # Para mapear tu código local al contenedor

networks:
  webnet:
    external: true
